### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by adamrich13** [kenthinson/Swift_Checkbox_Example#1]
Hello, 

I followed your tutorial and updated my code to swift 4 but every time I go to click my checkbox it crashes and shows the following can you help?
![Uploading Screen Shot 2019-01-06 at 5.52.23 PM.png…]()

**Comment by kenthinson** [comment]
I can't see the screen shot you are talking about. It seems it did not upload correctly. However I just tried the example project with iOS 12.2 it's working fine here.

**Comment by kenthinson** [comment]
Closing as I can't find a issue with the code. Hope you figured it out.
